spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret
          facebook:
            client-id: 1541816019295932
            client-secret: cd389cfabd54b39bd190aca4e5af2a42
      jwt:
        signkey : 123@#$

  datasource: # <- 추가
    url: jdbc:mysql://localhost:3306/cheoljin?characterEncoding=UTF-8&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true


custom:
  oauth2:
    kakao:
      client-id: e21cb4451ee07acedcbfa215bda04842
      client-secret: myCejtPUaiQnuTQc4QBqV3jiceGTzQAK


logging:
  level:
    com:
      community: debug

